# Generated by Django 3.1.3 on 2020-11-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='new',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='new',
            name='link',
            field=models.URLField(max_length=127, unique=True, verbose_name='Url'),
        ),
    ]
